MACHINE="hera"
ACCOUNT="fv3-cam"
EXPT_SUBDIR="test_nco_conus_25km_gfdl"

VERBOSE="TRUE"

RUN_ENVIR="nco"
PREEXISTING_DIR_METHOD="rename"

PREDEF_GRID_NAME="CONUS_25km_GFDLgrid"
QUILTING="TRUE"

CCPP_PHYS_SUITE="FV3_GFS_v15p2"

FCST_LEN_HRS="06"
LBC_SPEC_INTVL_HRS="3"

DATE_FIRST_CYCL="20210110"
DATE_LAST_CYCL="20210110"
CYCL_HRS=( "00" )

EXTRN_MDL_NAME_ICS="FV3GFS"
EXTRN_MDL_NAME_LBCS="FV3GFS"

RUN="srw_nco"
COMINgfs="/scratch1/NCEPDEV/rstprod/com/gfs/prod"    
FIXLAM_NCO_BASEDIR="/scratch2/NCEPDEV/fv3-cam/Chan-hoo.Jeon/00_DATA/fix_lam"  
STMP="/scratch2/NCEPDEV/fv3-cam/Chan-hoo.Jeon/01_OUT_DATA/stmp" 
PTMP="/scratch2/NCEPDEV/fv3-cam/Chan-hoo.Jeon/01_OUT_DATA/ptmp" 
